import { Inter, Bayon } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import NavbarMobile from "@/components/navbar-mobile";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const bayon = Bayon({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bayon",
});

export const metadata = {
  title: "Coin Camp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${bayon.variable}`}>
        <Providers>
          <div className="w-full flex items-center justify-center">
            <Header />
          </div>

          <NavbarMobile />
          <main className="w-full flex items-center justify-center">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
